# Generated by Django 3.2.7 on 2021-09-25 07:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('owner', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('image', models.TextField(blank=True, null=True)),
                ('reviews', models.TextField(max_length=2000)),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'UP VOTE'), ('down', 'Down VOTE')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Bathroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thrones_be.bathroom')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('preview_url', models.CharField(max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bathroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesUploads', to='thrones_be.bathroom')),
            ],
        ),
        migrations.AddField(
            model_name='bathroom',
            name='tags',
            field=models.ManyToManyField(blank=True, to='thrones_be.Tag'),
        ),
    ]
