# Generated by Django 3.2.7 on 2021-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrones_be', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='demo_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='bathroom',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bathroom',
            name='source_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
