# Generated by Django 3.2.7 on 2021-09-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
        ('thrones_be', '0002_auto_20210925_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
