# Generated by Django 3.2.7 on 2021-09-28 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
        ('thrones_be', '0003_bathroom_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Bathroom',
            new_name='bathroom',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'bathroom')},
        ),
    ]
